---
services:
  fscrawler:
    image: dadoonet/fscrawler:${FSCRAWLER_VERSION}
    container_name: fscrawler
    environment:
      - FS_JAVA_OPTS=${FS_JAVA_OPTS}
    volumes:
      - ../../test-documents/src/main/resources/documents/:/tmp/es:ro
      - ${PWD}/config:/root/.fscrawler
      - ${PWD}/logs:/usr/share/fscrawler/logs
      - ${PWD}/external:/usr/share/fscrawler/external
    ports:
      - ${FSCRAWLER_PORT}:8080
    command: idx --rest

