# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Pull Requests

on: [pull_request]

jobs:
  # We build the project but the docker images and run all the tests
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'
    - name: Docker Layer Caching
      uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
      with:
        key: fscrawler-docker-cache-{hash}
        restore-keys: |
          fscrawler-docker-cache-
    - name: Display Maven information
      run: mvn --version
    - name: Build but the docker images
      run: mvn --batch-mode install -Ddocker.skip -DskipTests

  # We run unit tests
  unit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: fscrawler-docker-cache-{hash}
          restore-keys: |
            fscrawler-docker-cache-
      - name: Run all the unit tests
        run: mvn --batch-mode install -Ddocker.skip -DskipIntegTests

  # We run integration tests with elastic stack 8 (default)
  it:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: fscrawler-docker-cache-{hash}
          restore-keys: |
            fscrawler-docker-cache-
      - name: Run the integration tests
        run: mvn --batch-mode install -Ddocker.skip -DskipUnitTests

  # We run integration tests with elastic stack 7
  it-es7:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: fscrawler-docker-cache-{hash}
          restore-keys: |
            fscrawler-docker-cache-
      - name: Run the integration tests
        run: mvn --batch-mode install -Ddocker.skip -DskipUnitTests -Pes-7x

  # We run integration tests with elastic stack 6
  it-es6:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: fscrawler-docker-cache-{hash}
          restore-keys: |
            fscrawler-docker-cache-
      - name: Run the integration tests
        run: mvn --batch-mode install -Ddocker.skip -DskipUnitTests -Pes-6x

  # We run this job in parallel after the build
  build-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: fscrawler-docker-cache-{hash}
          restore-keys: |
            fscrawler-docker-cache-
      - name: Build the docker images
        run: mvn --batch-mode install -DskipTests
